version: '3.8'

services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
    ports:
      - "3306:3306"

  user_service:
    build:
      context: ./user_service
    container_name: user_service
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
      - order_service
      - book_service
    env_file:
      - .env

  book_service:
    build:
      context: ./book_service
    container_name: book_service
    ports:
      - "8083:8083"
    depends_on:
      - mysql-db
    env_file:
      - .env

  order_service:
    build:
      context: ./order_service
    container_name: order_service
    ports:
      - "8086:8086"
    depends_on:
      - mysql-db
      - user_service
      - book_service
    env_file:
      - .env

  manager_service:
    build:
      context: ./manager_service
    container_name: manager_service
    ports:
      - "8084:8084"
    depends_on:
      - mysql-db
      - user_service
      - order_service
      - book_service
    env_file:
      - .env
