version: '3.8'

services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "8082:8082"
    depends_on:
      - user-db
    env_file:
      - .env
    environment:
      DB_URL: jdbc:mysql://user-db:3306/userdb

  user-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  book_service:
    build:
      context: ./book_service
    ports:
      - "8083:8083"
    depends_on:
      - book-db
    env_file:
      - .env
    environment:
      DB_URL: jdbc:mysql://book-db:3306/bookstore_db

  book-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: bookstore_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"

  order_service:
    build:
      context: ./order_service
    ports:
      - "8086:8086"
    depends_on:
      - order-db
      - user_service
      - book_service
    env_file:
      - .env
    environment:
      DB_URL: jdbc:mysql://order-db:3306/orderdb

  order-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"

  manager_service:
    build:
      context: ./manager_service
    ports:
      - "8084:8084"
    depends_on:
      - user_service
      - order_service
      - book_service
    env_file:
      - .env
